# Site settings
title: RHOLDY.COM 
email: holdy@holdy.dev
description: > # this means to ignore newlines until "baseurl:"
  Copyright 2022 -- Holdy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rholdy.com" # the base hostname & protocol for your site
twitter_username: ryan_holdaway

# Build settings
markdown: kramdown
